#DESAFIOS
#1)RECUPERAR  NOME E O ENDERECO DE TODOS OS FUNCIONARIOS QUE TRABALHAM
#PARA O DEPARTAMENTO "PESQUISA
SHOW TABLES;
SELECT * FROM TB_PROJETO;
DESC TB_DEPARTAMENTO;

SELECT F.PRIMEIRO_NOME, F.NOME_MEIO, F.ULTIMO_NOME, F.ENDERECO
FROM TB_DEPARTAMENTO D
INNER JOIN TB_FUNCIONARIO F
ON F.NUMERO_DEPARTAMENTO = D.NUMERO_DEPARTAMENTO
WHERE D.NOME_DEPARTAMENTO = "PESQUISA";

#2)PARA CADA PROJETO  LOCALIZADO EM MAUÁ, LISTE O NUMERO DO PROJETO, O NUMERO 
#DO DEPARTEMANTO QUE O CONTROLA E O ULTIMO NOME, ENDERECO E DATA DE NASCIMENTO DO GERENTE 
#DO DEPARTAMENTO
DESC TB_PROJETO;
DESC TB_DEPARTAMENTO;
DESC TB_LOCALIZACOES_DEPARTAMENTOS;

SELECT P.NUMERO_PROJETO, D.NUMERO_DEPARTAMENTO, F.ULTIMO_NOME, F.ENDERECO, F.DATA_NASCIMENTO,
D.NOME_DEPARTAMENTO 
FROM TB_PROJETO P
INNER JOIN TB_DEPARTAMENTO D
ON P.NUMERO_DEPARTAMENTO = D.NUMERO_DEPARTAMENTO
INNER JOIN TB_FUNCIONARIO F
ON F.CPF_FUNCIONARIO = D.CPF
WHERE P.LOCAL_PROJETO = 'MAUÁ';

#3) DESCOBRIR OS NOMES DOS FUNCIONARIOS QUE TRABALHAM EM TODOS OS PROJETOS
#CONTRALADOS PELO DEPARTAMENTO NUMERO 5

SELECT F.PRIMEIRO_NOME, F.NOME_MEIO, F.ULTIMO_NOME
FROM TB_FUNCIONARIO F
INNER JOIN TB_DEPARTAMENTO D
ON F.CPF_FUNCIONARIO = D.CPF
INNER JOIN TB_PROJETO P
ON P.NUMERO_DEPARTAMENTO = D.NUMERO_DEPARTAMENTO
WHERE P.NUMERO_DEPARTAMENTO = 5
GROUP BY F.PRIMEIRO_NOME, F.NOME_MEIO, F.ULTIMO_NOME;


#4) FAZER UMA LISTA DOS NUMEROS DE PROJETOS PARA AQUELES QUE ENVOLVEM UM 
#FUNCIONARIOS CUJO ULTIMO NOME É 'SOUSA'. SEJA COMO TRABALHADOR, SEJA 
#COMO GERENTE DO DEPARTAMENTO QUE CONTROLA O PROJETO

SELECT T.NUMERO_PROJETO FROM TB_FUNCIONARIO F
INNER JOIN TB_TRABALHA_EM T 
ON F.CPF_FUNCIONARIO = T.CPF
WHERE F.ULTIMO_NOME = 'Souza'
UNION
SELECT P.NUMERO_PROJETO FROM TB_FUNCIONARIO F
INNER JOIN TB_DEPARTAMENTO D
ON F.CPF_FUNCIONARIO = D.CPF
INNER JOIN TB_PROJETO P
ON P.NUMERO_DEPARTAMENTO = D.NUMERO_DEPARTAMENTO
WHERE F.ULTIMO_NOME = 'SOUZA';


#5) RECUPERE OS NOMES DO FUNCIONARIOS QUE NAO POSSUEM DEPENDENTES

SELECT F.PRIMEIRO_NOME, F.NOME_MEIO, F.ULTIMO_NOME FROM TB_FUNCIONARIO F
LEFT JOIN TB_DEPENDENTE D 
ON F.CPF_FUNCIONARIO = D.CPF
WHERE D.CPF IS NULL;

#6) LISTAR O NOME DOS GERENTES QUE POSSUEM PELO MENOS UM DEPENDENTE

SELECT DISTINCT F.PRIMEIRO_NOME, F.NOME_MEIO, F.ULTIMO_NOME
FROM TB_FUNCIONARIO F 
INNER JOIN TB_DEPENDENTE DE
ON F.CPF_FUNCIONARIO = DE.CPF
INNER JOIN TB_DEPARTAMENTO D 
ON F.CPF_FUNCIONARIO = D.CPF;


