SET FOREIGN_KEY_CHECKS =0;

DROP TABLE TB_DEPARTAMENTO;
DROP TABLE TB_DEPENDENTE;
DROP TABLE TB_FUNCIONARIO;
DROP TABLE TB_LOCALIZACOES_DEPARTAMENTOS;
DROP TABLE TB_PROJETO;
DROP TABLE TB_TRABALHA_EM;

SET FOREIGN_KEY_CHECKS =1;