SELECT * FROM TB_PROJETO;
SELECT NOME_PROJETO, NUMERO_PROJETO FROM TB_PROJETO;
SELECT NOME_PROJETO AS 'NOME DO PROJETO', 
NUMERO_PROJETO AS 'NUMERO DO PROJETO' FROM TB_PROJETO;

SELECT * FROM TB_PROJETO
WHERE LOCAL_PROJETO = 'Mauá';

SELECT * FROM TB_PROJETO
WHERE NUMERO_PROJETO = 10 AND NUMERO_DEPARTAMENTO =4;

SELECT * FROM TB_FUNCIONARIO;

SELECT * FROM TB_FUNCIONARIO
WHERE DATA_NASCIMENTO >= '1965-01-01';

SELECT * FROM TB_FUNCIONARIO
WHERE YEAR(DATA_NASCIMENTO) >= 1965;

SELECT * FROM TB_FUNCIONARIO
WHERE NUMERO_DEPARTAMENTO = 5;

SELECT CPF_FUNCIONARIO FROM TB_FUNCIONARIO
WHERE NUMERO_DEPARTAMENTO = 5
UNION
SELECT DISTINCT CPF FROM TB_FUNCIONARIO 
WHERE NUMERO_DEPARTAMENTO =5;

